name: carpooling_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.1.6

  cloud_firestore: ^5.6.6
  intl: ^0.19.0
  intl_phone_field: ^3.2.0
  url_launcher: ^6.2.2
  firebase_storage: ^12.4.5

  permission_handler: ^12.0.0+1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  geolocator: ^13.0.4
  flutter_typeahead: ^5.2.0
  http: ^1.3.0
  flutter_localization: ^0.3.2
  firebase_messaging: ^15.2.5

  flutter_local_notifications: ^19.0.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.0.17
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  google_mobile_ads: ^6.0.0
  flutter_webrtc: ^0.13.1+hotfix.1
  internet_connection_checker_plus: ^2.7.1
  wakelock_plus: ^1.2.11
  shimmer: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

